import type { Metadata } from "next";
import { PageHeader } from "@/components/site/page-header";
import { LegalBody } from "@/components/site/legal";

export const metadata: Metadata = {
  title: "Privacy policy",
  description: "How LendWise collects, uses and protects your information.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <PageHeader eyebrow="Legal" title="Privacy policy" />
      <LegalBody updated="25 September 2026">
        <p>LendWise is an educational demonstration platform. This policy explains what we collect when you use it and how we handle it.</p>
        <h2>Information we collect</h2>
        <ul>
          <li><strong>Identity & contact:</strong> full name, email address and mobile number.</li>
          <li><strong>Profile used by the model:</strong> age, marital status, profession, work experience, years in current job, annual income, city, state, house ownership, years at residence and car ownership.</li>
          <li><strong>Loan request:</strong> amount, tenure and purpose (recorded but not used by the model).</li>
          <li><strong>Technical:</strong> request identifiers and IP address for security and rate limiting. We do not use advertising trackers.</li>
        </ul>
        <h2>How we use it</h2>
        <ul>
          <li>To produce an automated risk assessment and decision for your application.</li>
          <li>To show your decision, generate your decision letter and let you check your status.</li>
          <li>To let authorised loan officers review decisions and record overrides.</li>
        </ul>
        <h2>Automated decision-making</h2>
        <p>
          Decisions are generated by a machine-learning model. You can see the main inputs and indicative factors on your decision page, and every decision can
          be reviewed by a human officer. See <a className="text-brand underline" href="/how-it-works">How it works</a> for details and limitations.
        </p>
        <h2>Security</h2>
        <p>
          Data is transmitted over HTTPS. Your decision page is available only in the browser you applied from (via a private, http-only cookie) or by entering
          your application ID together with your email. Officer access requires authentication. Personal details are never written to application logs.
        </p>
        <h2>Sharing</h2>
        <p>We do not sell or share your information with third parties for marketing. As a demo, LendWise does not share data with credit bureaus or lenders.</p>
        <h2>Retention & your choices</h2>
        <p>Demo data may be cleared periodically. To request deletion of an application, use the contact form with the topic “Privacy”, your application ID and the email you applied with. An officer will permanently delete the record.</p>
        <h2>Contact</h2>
        <p>Questions? Email support@lendwise.demo or use our <a className="text-brand underline" href="/contact">contact form</a>.</p>
      </LegalBody>
    </>
  );
}
