export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
export const SITE_NAME = "LendWise";

export const DISCLAIMER =
  "Decisions on LendWise are generated by a machine-learning risk model and are not an actual credit offer.";

export const NAV_LINKS = [
  { href: "/#products", label: "Loans" },
  { href: "/rates", label: "Rates & charges" },
  { href: "/#emi-calculator", label: "EMI calculator" },
  { href: "/how-it-works", label: "How we decide" },
  { href: "/faq", label: "Help" },
];

export const UTILITY_LINKS = [
  { href: "/rates", label: "Rates & charges" },
  { href: "/faq", label: "Help centre" },
  { href: "/contact", label: "Contact us" },
  { href: "/admin/login", label: "Officer login" },
];

export const PURPOSES = ["Personal", "Home", "Vehicle", "Education", "Business", "Medical", "Other"] as const;
